apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ include "birthdayapp.namespace" . }}
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: {{ include "birthdayapp.version" . }}
spec:
  replicas: {{ .Values.image.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/version: {{ include "birthdayapp.version" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          image: {{ include "birthdayapp.image" .Values.image.frontend }}
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.image.frontend.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
