{{- if .Values.networkPolicy.backend.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backend-cnp
  namespace: {{ include "birthdayapp.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      app: backend
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: frontend
        - matchLabels:
            app.kubernetes.io/name: ingress-nginx
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toCIDR:
        - {{ .Values.networkPolicy.backend.mongoCIDR | quote }}
      toPorts:
        - ports:
            - port: "27017"
              protocol: TCP
{{- end }}
