apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-internal
spec:
  ingressClassName: nginx-internal
  controllerNamePrefix: nginx-internal
  loadBalancerAnnotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy
  namespace: default
spec:
  ingressClassName: nginx-internal
  rules:
    - host: dummy.com
      http:
        paths:
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: dummy
                port:
                  number: 8080