
apiVersion: v1
kind: Pod
metadata:
  name: demo-insecure-pod
  namespace: birthdayapp
  labels:
    app: demo-insecure
  annotations:
    demo.security.example: "INSECURE_RESOURCE_DO_NOT_APPLY"
    purpose: "trivy-misconfig-demo"
spec:
  hostNetwork: true
  hostPID: true
  containers:
    - name: insecure
      image: busybox:1.34
      command: ['sh','-c','sleep 3600']
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
        capabilities:
          add: ["ALL"]
      resources: {}
      volumeMounts:
        - name: host
          mountPath: /host
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
